### ISSUE TITLE
Install-SecDrv fails

### ISSUE THREAD

**Issue by uwks911** [ericwj/PsSecDrv#1]
When launching command Install-SecDrv it throws an error:

 Install-Package : Не удалось найти поставщики пакетов (PSModule).
C:\Users\root\Documents\WindowsPowerShell\Modules\SECDRV\SECDRV.psm1:198 знак:9
+         Install-Package -Name ($PswuSpec.ModuleName) -ProviderName PS ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPack
   age:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageMan
   agement.Cmdlets.InstallPackage

The required package PSWindowsUpdate could not be obtained. This may be due to
connectivity problems, or a version conflict. Try again later.
C:\Users\root\Documents\WindowsPowerShell\Modules\SECDRV\SECDRV.psm1:201 знак:1
3
+             throw "The required package PSWindowsUpdate could not be  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The required pa...ry again la
   ter.:String) [], RuntimeException
    + FullyQualifiedErrorId : The required package PSWindowsUpdate could not b
   e obtained. This may be due to connectivity problems, or a version conflic
  t. Try again later.

**Comment by ericwj** [comment]
This script is old.

I only tested this a long time ago on Windows 10 prior to 14393. You don't need the update anymore that the script tries to install using the PSWindowsUpdate module.

I updated the readme, read it.

You can try to download and run PsSecDrv/src/Scripts/QuickFix.ps1 instead. I recommend you step through it with *Windows PowerShell ISE*.
