### ISSUE TITLE
SignTool Error: Invalid SHA1 hash format: /t

### ISSUE THREAD

**Issue by KSenfiz** [ericwj/PsSecDrv#11]
Hello, I followed your tutorial to the letter, but at
![image](https://github.com/ericwj/PsSecDrv/assets/39855514/252e250c-2645-4a44-a519-9b3405b8050f)
part i get
![image](https://github.com/ericwj/PsSecDrv/assets/39855514/b72b6a4c-3f05-4e82-a044-584985a707e4)
and  I don't knnow why.After I wen to look trough closed Issues to see If someone else got the same problem and got it solved, but only found a perculiar issue at https://github.com/ericwj/PsSecDrv/issues/5 where appearantly user got a different output in PowerShell at command
![image](https://github.com/ericwj/PsSecDrv/assets/39855514/6c802c15-0e96-4829-b555-8c2158cfe754)
for him PowerShell returned with
![image](https://github.com/ericwj/PsSecDrv/assets/39855514/51c9c9f2-85da-4763-93d2-34d191adfa32)
but for me it's
![image](https://github.com/ericwj/PsSecDrv/assets/39855514/7008260b-17d6-40c5-8288-a69c5e101422)
and I seriously dunno what to do and would rreally appreciate if you could enlighten me where I go worng. If you need more information please let me know.

**Comment by HelpfulFriend** [comment]
This issue happens if you forget to drop the self signed certificate in the "trustedPublisher" folder in certlm. If you look at the script. It pulls the certificate from CERT:\LocalMachine\TrustedPublisher.
so if your $publishers variable is empy you will not get the thumbprint, thereby not be able to sign it.

**Comment by ericwj** [comment]
Yes, that is most likely the culprit.

Remember you can always inspect every variable and see where it goes wrong, since it is simple plain text script code.
