### ISSUE TITLE
Game won't launch with ripped CD-ROM ISO image mounted

### ISSUE THREAD

**Issue by Evan-Burch** [ericwj/PsSecDrv#13]
Hello, the last few days I have been trying to get Medal of Honor Allied Assault working as a birthday present for my father. This repository looks like exactly what I need to solve the secdrv issue. I went through all of the steps in the README once with no issues (aside from having to reboot in order to disable Secure Boot). Although the game continues to give me "Please insert the correct CD_ROM, select OK and restart application" when I run it as administrator. The game requires 2 disks, and I have both iso files mounted when running the game exe. 

After this, I decided to completely uninstall and reinstall the game files, as well as restart the README process and document each step. I am running 64-bit Windows 10.
- I ran the game once as administrator and saw the SECDRV.SYS file appear at C:\Windows\SysWOW64\drivers
- I installed the Windows 10 SDK from the link
- Here is the powershell output of the commands I ran. The secdrv.sys included with the game was 32-bit so I used curl to get the secdrv.sys from github. I added the cert to Trusted Root Certification Authorities and Trusted Publishers. 
![powershell_output1](https://github.com/user-attachments/assets/52e93436-367e-46c2-9911-395b6a501a9a)
![powershell_output2](https://github.com/user-attachments/assets/35aabf64-7934-4edb-91e4-faf3976a37b8)
After shutting down and turning on pc again, I started up the secdrv service right away without issue as seen below.
![powershell_output3](https://github.com/user-attachments/assets/33182d66-48c6-43de-983a-b2a121eac1b5)
I also can confirm that I have the text in the corner saying I am in Test Mode. 

After all of this, I still can not launch the game. I get the same message about needing to insert the disk. I would love any assistance on debugging if the driver is working as this repository intends or not, or if I am dealing with some other issue.  By the way, before I found this repository, I was seeing events in the Event Viewer about secdrv.sys being blocked whenever I ran the game. I no longer see those events. Thank you for the detail you have put into the README, as well as the other issue responses. They indirectly helped me understand some things, even though they did not solve my issue.

**Comment by ericwj** [comment]
The goal of `SECDRV.sys` is to verify that you didn't just rip and burn the original physical CD-ROM.

Unless you can fake the intentionally manufactured bad sectors to produce hardware errors through which `SECDRV.sys` does this verification and you can make the timing of read errors believable for the driver, running from `.iso` won't work.

For many games you can find cracks which circumvent the requirement to have the original CD-ROM in the drive. These usually then also complete erase the need to have `SECDRV.sys` installed at all. However that is considered piracy and as always you run these cracks or any software you download from anonymous people on the Internet at your own peril.
