### ISSUE TITLE
[SC] StartService: OpenService FAILED 1060:  The specified service does not exist as an installed service.

### ISSUE THREAD

**Issue by Velorok19** [ericwj/PsSecDrv#3]
Hi, I'm on Win 10 Enterprise LTSC N latest. Tried your guide:
Got cert installed. Copied secdrv.sys from pulled github link into C:\Windows\SysWOW64\drivers and C:\Windows\System32\drivers but still getting this after restart (windows in test mode):

```
PS C:\WINDOWS\system32> & cmd /c sc start secdrv.sys
[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.

PS C:\WINDOWS\system32>
```

**Comment by ericwj** [comment]
The Windows Service is called `secdrv` not `secdrv.sys`.

**Comment by OkazakiNaoki** [comment]
I type it without .sys still show me this info.

- No secure boot checked
- Downloaded .sys from your git
- Run powershell as Administrator
- Rebooted

And the command before this are all success.
Do you have any idea what else might cause this?

**Comment by ericwj** [comment]
That error only happens if the service just isn't there. Try 

```PS
Get-Service secdrv
```
in PowerShell and verify that you don't get 

```
Get-Service: Cannot find any service with service name 'secdrv'.
```
as an answer.

If you do get this error then something went wrong installing the driver service. Start over and make sure every step is successful or document the errors you are getting so you can diagnose those or post them here.

**Comment by vaibhavip-icpl** [comment]
i got same error when i'm  going to remove services using remove service from service.
![image](https://user-images.githubusercontent.com/103485015/171599655-a61b72d3-6926-4146-acf8-b303235d2b6f.png)
