### ISSUE TITLE
SECDRV.sys Self-Sign - Need help with adding Environment Variable Path

### ISSUE THREAD

**Issue by rarndtjr** [ericwj/PsSecDrv#4]
Greetings,  I need some help with the instructions for setting the SDK Tools Path in the System Environment Variable path to perform self-sign of secdrv.sys driver as noted here:
https://github.com/ericwj/PsSecDrv

In the instructions it states, "Find makecat.exe, makecert.exe and signtool.exe and add the path to your PATH in System Properties, Environment Variables.
The ones in a x86 subfolder are always OK on all Intel architecture chips. No need to match the hardware or the OS bitness."

However, for (makecat.exe, makecert.exe and signtool.exe), the path is "C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86" 

Q: What is the $SdkToolsPath referenced below used for?
Q: Is this $SdkToolsPath below required or can I simply add the path (above) to System EV?

Note: if I execute the command script below within PS, the command completes but it does not update the System EV Path so I'm confused on how to use the $SdkToolsPath below.
![how_to_install_secdrv_sys_to_play_games](https://user-images.githubusercontent.com/11206608/80893540-155bcc80-8c88-11ea-9b0f-6550f47063cf.png)

Q: How do I use the $SdkToolsPath referenced below?

$SdkToolsPath = dir -Path "${env:ProgramFiles(x86)}\Windows Kits\10" -Recurse -Directory | where { $n = $_.FullName; $_.BaseName -eq "x86" -and [System.IO.File]::Exists("$n\makecert.exe") -and [System.IO.File]::Exists("$n\makecat.exe") -and [System.IO.File]::Exists("$n\signtool.exe") } | sort CreationTime | select -Last 1
$env:Path = "$env:Path;$($SdkToolsPath.FullName)"

Thanks.

**Comment by ericwj** [comment]
> Q: What is the $SdkToolsPath referenced below used for?
> Q: Is this $SdkToolsPath below required or can I simply add the path (above) to System EV?

Of course you could do it by hand but

> Q: How do I use the $SdkToolsPath referenced below?

well the script in fact does it for you.

`$SdkToolsPath` is just a PowerShell variable. It is in fact a [FileSystemInfo](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo) so the `FullName` property is the full path -- which is added to the `PATH` environment variable in the second line that you put a red box around.

The command (split at each pipe character `|`) is doing this all in one line of code:
* List all directories recursively under C:\Program Files (x86)\Windows Kits\10
* Filter out all directories for which all of the following is true
  * The directory's leaf name is `x86`
  * The directory contains `makecert.exe`
  * The directory contains `makecat.exe`
  * The directory contains `signtool.exe`
* Sort the directories by creation time
* Select the last one

Then it adds its full path to the `PATH` environment variable (`$env:Path = ...`).

**Comment by rarndtjr** [comment]
Thanks Eric,

I was able to successfully self-sign but needed to make a few modifications to the step-by-step process above (as some of the commands would not work even with Admin privileges).  Unfortunately, after successful self-signing SECDRV.sys, the final "test" step failed with error similar to "SECDRV.sys was not allowed to start" (although all recommended pre-requisites were satisfied:

- PS opened as Administrator or you opened the PowerShell prompt without elevation.
- SECDRV.sys is latest (Win 8.1) v4.03.086 2006/09/13
- Secure Boot is Disabled
- System has been rebooted multiple times

I will open a separate ticket and include the exact steps used and results and if you can take a look that would be great.

Regards,

Ron
