### ISSUE TITLE
SECDRV failing to install while signing the driver

### ISSUE THREAD

**Issue by BEENNath58** [ericwj/PsSecDrv#6]
I was able to go through all the steps without any error but it fails during the signing process.
![secdrvfail (2)](https://user-images.githubusercontent.com/64649734/111901344-89988d80-8a5d-11eb-8d6a-3d8b09f669c1.png)

**Comment by ericwj** [comment]
That might be a temporary problem because the server may have had issues. Did you try again at least a few hours later?

**Comment by ericwj** [comment]
I verified that the mentioned timestamp server did (still) not work just now.

I updated the readme with a new timestamping server URL, following the instructions at [Test-Signing a Driver Package's Catalog File - Windows drivers | Microsoft Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/test-signing-a-driver-package-s-catalog-file).
