### ISSUE TITLE
Windows 10 seems to be deleting secdrv.sys automatically now

### ISSUE THREAD

**Issue by ghost** [ericwj/PsSecDrv#7]
I went through all the steps to re-enable secdrv through powershell, and appeared to have the desired result, but upon reboot, secdrv.sys simply disappears from the system32/drivers folder, and the service can't be found.

**Comment by ericwj** [comment]
It didn't for me. I just verified today that it is working as expected on Windows 11.

You could have anti-virus problems. Disable real time protection at least temporarily while you download and move SECDRV.sys around. After that, you might have to fiddle with exceptions or exclusions if the file goes missing again.

Also do check the readme again - I made two changes that might correct some issues which people might run into on recent versions of Windows 10 and 11.
